# Generated by Django 4.0.3 on 2022-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_alter_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('users', 'users'), ('products', 'products'), ('products', 'revievs'), ('products', 'comments'), ('products', 'files'), ('products', 'messages')], max_length=10),
        ),
    ]
