# Generated by Django 4.0.3 on 2022-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_alter_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.IntegerField(choices=[(1, 'users'), (2, 'products'), (3, 'revievs'), (4, 'comments'), (5, 'files'), (6, 'messages')]),
        ),
    ]
