# Generated by Django 4.0.3 on 2022-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0006_alter_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
